project_name: inaccel

before:
  hooks:
  - go mod download
builds:
- binary: inacceld
  env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  main: ./cmd

archives:
- files:
  - none*
  id: archive
  name_template: "{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: checksums.txt
dockers:
- build_flag_templates:
  - "--label=org.opencontainers.image.authors=InAccel <info@inaccel.com>"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.description=InAccel is a product for you to build, ship and run hardware accelerated applications"
  - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://inaccel.com"
  - "--label=org.opencontainers.image.vendor=InAccel"
  - "--label=org.opencontainers.image.version={{ .RawVersion }}"
  image_templates:
  - inaccel/daemon:latest
  - inaccel/daemon:{{ .RawVersion }}
nfpms:
- bindir: /usr/bin
  contents:
  - dst: /etc/containers/containers.conf
    src: configs/containers/containers.conf
    type: config|noreplace
  - dst: /etc/systemd/system/inaccel.service.d/override.conf
    src: configs/systemd/override.conf
    type: config|noreplace
  - dst: /etc/systemd/system/inaccel.service
    src: init/systemd/inaccel.service
  description: InAccel is a product for you to build, ship and run hardware accelerated applications
  file_name_template: "{{ .ConventionalFileName }}"
  formats:
  - deb
  - rpm
  homepage: https://inaccel.com
  license: Apache-2.0
  maintainer: InAccel <info@inaccel.com>
  vendor: InAccel
release:
  footer: |
    ## Docker images

    - `docker pull inaccel/daemon:{{ .RawVersion }}`
